CREATE TABLE IF NOT EXISTS Poll (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    createAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PollOption (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    pollId TEXT NOT NULL,
    FOREIGN KEY (pollId) REFERENCES Poll(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE SEQUENCE IF NOT EXISTS "Vote_id_seq";
CREATE TABLE IF NOT EXISTS Vote (
    id INTEGER PRIMARY KEY DEFAULT nextval('"Vote_id_seq"'::regclass),
    sessionId TEXT NOT NULL,
    pollId TEXT NOT NULL,
    pollOptionId TEXT NOT NULL,
    createAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sessionId, pollId),
    FOREIGN KEY (pollId) REFERENCES Poll(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (pollOptionId) REFERENCES PollOption(id) ON UPDATE CASCADE ON DELETE RESTRICT
)