
CREATE TABLE IF NOT EXISTS Users (
    Id TEXT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    Nickname TEXT NOT NULL,
    Email TEXT NOT NULL,
    Password TEXT NOT NULL,
    Image BYTEA,
    CreateAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE statusType AS ENUM ('pending', 'finish', 'open');
CREATE TABLE IF NOT EXISTS Poll (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status statusType,
    createAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PollOption (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    pollId TEXT NOT NULL,
    FOREIGN KEY (pollId) REFERENCES Poll(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE SEQUENCE IF NOT EXISTS "Vote_id_seq";
CREATE TABLE IF NOT EXISTS Vote (
    id INTEGER PRIMARY KEY DEFAULT nextval('"Vote_id_seq"'::regclass),
    sessionId TEXT NOT NULL,
    pollId TEXT NOT NULL,
    pollOptionId TEXT NOT NULL,
    createAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sessionId, pollId),
    FOREIGN KEY (pollId) REFERENCES Poll(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (pollOptionId) REFERENCES PollOption(id) ON UPDATE CASCADE ON DELETE RESTRICT
)