// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Poll struct {
	ID       string
	Title    string
	Createat time.Time
	Updateat time.Time
}

type Polloption struct {
	ID     string
	Title  string
	Pollid string
}

type Vote struct {
	ID           int32
	Sessionid    string
	Pollid       string
	Polloptionid string
	Createat     time.Time
}
