// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const createPoll = `-- name: CreatePoll :exec
INSERT INTO Poll(id, title, createAt, updateAt)
VALUES($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreatePollParams struct {
	ID    string
	Title string
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) error {
	_, err := q.db.ExecContext(ctx, createPoll, arg.ID, arg.Title)
	return err
}
